In [2]:
import numpy as np
agent_obs_shape = (1, 10)  # 假设原始形状
global_obs_shape = (1, 5, 1)  # 假设原始形状
action_shape = (1,)  # 假设原始形状

# 使用自定义的 squeeze 函数
def squeeze(shape):
    if isinstance(shape, (list, tuple)):
        return int(np.prod([dim for dim in shape if dim != 1]))
    return shape

agent_obs_shape = squeeze(agent_obs_shape)  # 结果为 10
global_obs_shape = squeeze(global_obs_shape)  # 结果为 (5,)
action_shape = squeeze(action_shape)  # 结果为 1

print(f"agent_obs_shape: {agent_obs_shape}")
print(f"global_obs_shape: {global_obs_shape}")
print(f"action_shape: {action_shape}")

agent_obs_shape: 10
global_obs_shape: 5
action_shape: 1


In [24]:
import unittest
import torch
import torch.nn as nn

class TestNNLinear(unittest.TestCase):
    def setUp(self):
        # 初始化一个简单的 nn.Linear 层
        self.linear = nn.Linear(in_features=3, out_features=2, bias=True)
        # 设置固定的权重和偏置以便测试
        self.linear.weight.data = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
        self.linear.bias.data = torch.tensor([0.1, 0.2])

    def test_forward(self):
        # 创建一个输入张量
        input_tensor = torch.tensor([[1.0, 2.0, 3.0]])
        # 计算期望的输出
        expected_output = torch.tensor([[14.1, 32.2]])
        # 获取实际输出
        output = self.linear(input_tensor)
        # 检查输出是否与期望输出一致
        self.assertTrue(torch.allclose(output, expected_output, atol=1e-6))

# if __name__ == '__main__':
#     unittest.main()

In [25]:
unittest_main = TestNNLinear()

In [26]:
unittest_main.setUp()
unittest_main.test_forward()


In [29]:
# nn.Sequential 是 PyTorch 中用于按顺序堆叠多个模块的容器。
# 可以简化模型的定义，特别是在需要连续应用多个层时。

In [47]:
class TestNNSequential(unittest.TestCase):
    def setUp(self):
        # 初始化一个 nn.Sequential 模型
        self.model = nn.Sequential(
            nn.Linear(in_features=3, out_features=4, bias=True),
            nn.ReLU(),
            nn.Linear(in_features=4, out_features=2, bias=True)
        )
        # 设置固定的权重和偏置以便测试
        self.model[0].weight.data = torch.tensor([
            [1.0, 2.0, 3.0],
            [4.0, 5.0, 6.0],
            [7.0, 8.0, 9.0],
            [10.0, 11.0, 12.0]
        ])
        self.model[0].bias.data = torch.tensor([0.1, 0.2, 0.3, 0.4])
        self.model[2].weight.data = torch.tensor([
            [13.0, 14.0, 15.0, 16.0],
            [17.0, 18.0, 19.0, 20.0]
        ])
        self.model[2].bias.data = torch.tensor([0.5, 0.6])

    def test_forward(self):
        # 创建一个输入张量
        input_tensor = torch.tensor([[1.0, 2.0, 3.0]])
        
        # 计算每一层的输出
        # 第一层输出: [10.1, 25.2, 40.3, 55.4]
        first_layer_output = self.model[0](input_tensor)
        print(f"First Layer Output: {first_layer_output}")
        
        # ReLU 后: [10.1, 25.2, 40.3, 55.4]
        relu_output = self.model[1](first_layer_output)
        print(f"ReLU Output: {relu_output}")
        
        # 第二层输出: [2483.5, 3144.6]
        second_layer_output = self.model[2](relu_output)
        print(f"Second Layer Output: {second_layer_output}")
        
        # 计算期望的输出
        expected_output = torch.tensor([[2483.5, 3143.6]])
        
        # 获取实际输出
        output = self.model(input_tensor)
        print(f"Model Output: {output}")
        
        # 检查输出是否与期望输出一致
        self.assertTrue(torch.allclose(output, expected_output, atol=1e-1))

In [48]:
sequential_test = TestNNSequential()

sequential_test.setUp()
sequential_test.test_forward()

First Layer Output: tensor([[14.1000, 32.2000, 50.3000, 68.4000]], grad_fn=<AddmmBackward0>)
ReLU Output: tensor([[14.1000, 32.2000, 50.3000, 68.4000]], grad_fn=<ReluBackward0>)
Second Layer Output: tensor([[2483.5000, 3143.6001]], grad_fn=<AddmmBackward0>)
Model Output: tensor([[2483.5000, 3143.6001]], grad_fn=<AddmmBackward0>)


In [38]:
sequential_test.model

Sequential(
  (0): Linear(in_features=3, out_features=4, bias=True)
  (1): ReLU()
  (2): Linear(in_features=4, out_features=2, bias=True)
)

In [33]:
sequential_test.model[0]._parameters

{'weight': Parameter containing:
 tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.],
         [10., 11., 12.]], requires_grad=True),
 'bias': Parameter containing:
 tensor([0.1000, 0.2000, 0.3000, 0.4000], requires_grad=True)}

In [35]:
sequential_test.model[2]._parameters


{'weight': Parameter containing:
 tensor([[13., 14., 15., 16.],
         [17., 18., 19., 20.]], requires_grad=True),
 'bias': Parameter containing:
 tensor([0.5000, 0.6000], requires_grad=True)}

In [36]:
sequential_test.model


Sequential(
  (0): Linear(in_features=3, out_features=4, bias=True)
  (1): ReLU()
  (2): Linear(in_features=4, out_features=2, bias=True)
)